"""
Generate (problem, answer) pairs for the Gröbner basis computation task.

Math
----
R = k[x, y],  k ∈ {QQ, GF(7), ZZ}
I = ⟨f1, f2⟩  (ideal generated by two polynomials)

Given f1, f2 ∈ R sampled at random:
  - G = degrevlex Gröbner basis of I  (Buchberger's algorithm via SageMath)

The learning task is: given (f1, f2), predict G.

Reference
---------
Mirrors `issac2026_experiments/groebner/generate_dataset.py` from the
HiroshiKERA/calt branch experiment/issac2026.
"""

import sage.all  # noqa: F401  # ensure Sage is initialised before any submodule import
import sage.misc.randstate as randstate  # type: ignore
from sage.rings.rational_field import QQ  # type: ignore

from calt.dataset.sagemath.utils.polynomial_sampler import PolynomialSampler


def _has_large_rational_coefficients(polynomials, threshold: int = 100) -> bool:
    """
    Return True if any polynomial has a rational coefficient whose numerator OR
    denominator has |value| ≥ threshold.

    Used to reject samples with Buchberger coefficient swell over QQ.
    For non-QQ fields (GF(p), ZZ) this check is silently skipped per coefficient.
    """
    for p in polynomials:
        for c in p.coefficients():
            try:
                num = c.numerator()
                den = c.denominator()
            except Exception:
                continue
            if abs(int(num)) >= threshold or abs(int(den)) >= threshold:
                return True
    return False


class GroebnerGenerator:
    """
    Problem generator: F = [f1, ..., f_{num_polynomials}], answer = Gröbner basis of ⟨F⟩.

    Returns SageMath polynomial objects; the CALT DatasetPipeline converts them
    to strings via str() and joins with ' | '.

    Parameters
    ----------
    sampler : PolynomialSampler
        Builds the random polynomials in the chosen ring.
    num_polynomials : int
        Number of generators (default 2).
    """

    def __init__(self, sampler: PolynomialSampler, num_polynomials: int = 2):
        self.sampler = sampler
        self.num_polynomials = num_polynomials

    def __call__(self, seed: int) -> tuple[list, list]:
        randstate.set_random_seed(seed)

        R = self.sampler.get_ring()
        is_QQ = R.base_ring() == QQ

        # For QQ only: reject samples with rational coefficients ≥ 3 digits in numerator or denominator
        max_retries = 100
        last_F, last_G = None, None
        for _ in range(max_retries):
            F = self.sampler.sample(num_samples=self.num_polynomials)
            ideal = R.ideal(F)
            G = list(ideal.groebner_basis())
            last_F, last_G = F, G

            if not is_QQ:
                break
            if not _has_large_rational_coefficients(list(F) + list(G), threshold=100):
                break

        return last_F, last_G
